[colors.primary]
background = "#070f12"
foreground = "#c1c3c3"

[colors.cursor]
text = "#070f12"
cursor = "#c1c3c3"

[colors.vi_mode_cursor]
text = "#070f12"
cursor = "#c1c3c3"

[colors.search.matches]
foreground = "#070f12"
background = "#c1c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#56676a"
background = "#c1c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#070f12"
red = "#063C44"
green = "#0C4E4B"
yellow = "#136759"
blue = "#119B5C"
magenta = "#23C253"
cyan = "#8AE45E"
white = "#c1c3c3"

[colors.bright]
black = "#56676a"
red = "#063C44"
green = "#0C4E4B"
yellow = "#136759"
blue = "#119B5C"
magenta = "#23C253"
cyan = "#8AE45E"
white = "#c1c3c3"

[colors.dim]
black = "#c1c3c3"
red = "#063C44"
green = "#23C253"
yellow = "#136759"
blue = "#119B5C"
magenta = "#0C4E4B"
cyan = "#8AE45E"
white = "#56676a"

