[colors]
background = '#070f128e'
black = '#070f12'
blue = '#063C44'
cursor = '#c1c3c3'
cyan = '#0C4E4B'
foreground = '#c1c3c3'
green = '#136759'
magenta = '#119B5C'
red = '#23C253'
tabs = '#c1c3c3'
tabs-active = '#8AE45E'
white = '#c1c3c3'
yellow = '#c1c3c3'
dim-black = '#070f128e'
dim-blue = '#063C448e'
dim-cyan = '#0C4E4B8e'
dim-foreground = '#c1c3c38e'
dim-green = '#1367598e'
dim-magenta = '#119B5C8e'
dim-red = '#23C2538e'
dim-white = '#8AE45E8e'
dim-yellow = '#c1c3c38e'
light-black = '#063C44'
light-blue = '#0C4E4B'
light-cyan = '#136759'
light-foreground = '#119B5C'
light-green = '#23C253'
light-magenta = '#8AE45E'
light-red = '#c1c3c3'
light-white = '#063C44'
light-yellow = '#0C4E4B'
